export const INCREMENT_MUTATION = "INCREMENT_MUTATION";
export const GROWUP_MUTATION = "GROWUP_MUTATION";
export const INACTIONB_MUTATION = "INACTIONB_MUTATION";
export const AGERISE_MUTATION = "AGEPLUS_MUTATION";
export const LGSAME_MUTATION = "LGSAME_MUTATION";

