export const INCREMENT_MUTATION = "INCREMENT_MUTATION";
export const GROWUP_MUTATION = "GROWUP_MUTATION";
export const INACTIONA_MUTATION = "INACTIONA_MUTATION";
export const INACTIONB_MUTATION = "INACTIONB_MUTATION";
export const INACTIONC_MUTATION = "INACTIONC_MUTATION";

